# Generated by Django 4.2.7 on 2023-12-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('idmecanico', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('especialidade', models.CharField(max_length=100)),
            ],
        ),
    ]
