# Generated by Django 4.2.7 on 2023-12-03 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mecanicos', '0002_alter_mecanico_table_equipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='mecanico',
            field=models.ForeignKey(db_column='mecanico_idmecanico', on_delete=django.db.models.deletion.CASCADE, to='mecanicos.mecanico'),
        ),
    ]
