# Generated by Django 4.2.7 on 2023-12-04 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecanicos', '0003_alter_equipe_mecanico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='id',
        ),
        migrations.AddField(
            model_name='equipe',
            name='idequipe',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
