# Generated by Django 4.2.7 on 2023-12-03 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('idveiculo', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=7)),
                ('ano', models.IntegerField()),
                ('problema', models.TextField()),
                ('cliente', models.ForeignKey(db_column='cliente_idcliente', on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
            options={
                'db_table': 'veiculo',
            },
        ),
    ]
